#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

CMD="${TRIM_APPDEST}/app/server/easytier-core"
WEB_CMD="${TRIM_APPDEST}/app/server/easytier-web-embed"
WEB_PID_FILE="${TRIM_PKGVAR}/web.pid"
WEB_LOG_FILE="${TRIM_PKGVAR}/web.log"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0
    else
        return 1
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            rm -f "${PID_FILE}"
        fi
    fi
    return 1
}

start_process() {
    if status; then
        return 0
    fi

    log_msg "Starting easytier-core ..."
    bash -c "${CMD}" >> ${LOG_FILE} 2>&1 &
    printf "%s" "$!" > ${PID_FILE}
    return 0
}

start_web() {
    log_msg "Starting web panel..."
    bash -c "${WEB_CMD} --api-server-port 11211" >> ${WEB_LOG_FILE} 2>&1 &
    printf "%s" "$!" > ${WEB_PID_FILE}
}

stop_process() {
    log_msg "Stopping easytier-core ..."

    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')

        log_msg "pid=${pid}"
        if ! check_process "${pid}"; then
            rm -f "${PID_FILE}"
            log_msg "remove pid file 1"
            return
        fi

        log_msg "send TERM signal to PID:${pid}..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "waiting process terminal... (${count}s/10s)"
        done

        if check_process "${pid}"; then
            log_msg "send KILL signal to PID:${pid}..."
            kill -KILL "${pid}"
            sleep 1
            rm -f "${PID_FILE}"
        else
            log_msg "process killed... "
        fi
    fi

    return 0
}

stop_web() {
    log_msg "Stopping web panel..."
    if [ -r "${WEB_PID_FILE}" ]; then
        pid=$(head -n 1 "${WEB_PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            kill -TERM ${pid} 2>/dev/null
            sleep 2
            if check_process "${pid}"; then
                kill -KILL "${pid}" 2>/dev/null
            fi
        fi
        rm -f "${WEB_PID_FILE}"
    fi
}

case $1 in
start)
    start_process
    start_web
    ;;
stop)
    stop_process
    stop_web
    ;;
status)
    if status; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
